### ISSUE TITLE
how to build the test file?

### ISSUE THREAD

**Issue by N0ah10f1** [Yuki-11/CSBSR#1] opened 2024-05-12 02:00 UTC
The test file should consider a config.yaml, images and a model files which save the weights? in the Usege, why does it create a weights folder? python test.py weights/CSBSR_w_PSPNet_beta03/latest --sf_save_image

Thank you

**Comment by Yuki-11** [comment] 2024-05-12 08:33
Hello,

Thank you for bringing up these questions regarding the test setup and configuration. Let me address each of your points for clarity:

1. Configuration and Model Files: Yes, it is necessary to consider both the config and model files. The config file is recognized from the directory specified in the first command-line argument, under config.yaml. For the model files, you should use the second command-line argument to specify either the iteration number or the model file name, excluding the extension. There is no need to explicitly specify images in test.py, and the --sf_save_image is an optional argument that if  used, means that the output images will not be saved.

2. Creation of a Weights Folder: You are correct in assuming that the folder is created to store the weight files that I have made publicly available. This setup is intended to keep the workflow organized and ensure that weight files are easily accessible during testing.

![image](https://github.com/Yuki-11/CSBSR/assets/62691917/9efd609d-0b43-4285-a5d9-0a7b4820ce23)

3. Usage Correction: Regarding the usage in the README, I apologize for the confusion caused by the error. The correct command should indeed be:

`python test.py weights/CSBSR_w_PSPNet_beta03 latest --sf_save_image`

Please let me know if you need further clarification on any of these points, or if there's anything else I can assist you with.

Best regards,

**Comment by Yuki-11** [comment] 2024-06-29 06:39
I have not received any further responses regarding the issue raised in `how to build the test file? #1`. As a result, I am assuming that the problem has been resolved. Therefore, I will proceed to close this issue.

If the problem persists or you have any additional concerns, please feel free to reopen the issue or create a new one.

Thank you for your understanding and cooperation.

**Closed as completed by Yuki-11** 2024-06-29 06:39 UTC
